name: appatonce
description: Official Flutter SDK for AppAtOnce unified backend platform
version: 0.1.1
homepage: https://github.com/appatonce/flutter-sdk
repository: https://github.com/appatonce/flutter-sdk

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  http: ^1.1.0
  socket_io_client: ^2.0.3+1
  dio: ^5.3.2
  rxdart: ^0.27.7
  shared_preferences: ^2.2.1
  connectivity_plus: ^5.0.1
  path_provider: ^2.1.1
  crypto: ^3.0.3
  json_annotation: ^4.9.0
  mime: ^1.0.4
  equatable: ^2.0.5
  flutter_secure_storage: ^9.0.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  mockito: ^5.4.2
  flutter_lints: ^3.0.0
  test: ^1.24.3
  yaml: ^3.1.2

scripts:
  test: flutter test
  test:watch: flutter test --watch
  test:coverage: flutter test --coverage
  test:comprehensive: dart test/test_runner.dart
  test:all: ./test/run_tests.sh
  lint: flutter analyze
  lint:fix: dart fix --apply
  build: flutter packages pub run build_runner build
  build:watch: flutter packages pub run build_runner watch